version: '3.8'

services:

  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  cubiculos-service:
    build:
      context: ./cubiculos_backend
      dockerfile: Dockerfile
    container_name: cubiculo-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - cubiculos-service
    networks:
      - microservices-network
      
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8093"
    depends_on:
      - eureka-server
    networks:
      - microservices-network


volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge

